[project]
name = "rockets-revenge"
version = "0.1.0"
description = "A small game made with Pyxel utilizing a scrolling dungeon."
readme = "README.md"
requires-python = ">=3.13.7"
dependencies = [
    "pyxel>=2.5.8",
]
